# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ba16a31bd7870f52bcf5a8eecfd551acef1ed26854c9ae5bfaef9e762c348828dba8c151c2676b0ea884646d8d8df559e64c1d2675d6ea00236a3b62677b6a6

test:
  secret_key_base: 9f1d9388c8c4e8a325a19f3765dd101dfaa673e90a64ce276169cb09a8dac81cde1957692aa2edd5a4e2747e83d6461f3b1ee1d5d707b5307d3fd438e7986569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
